package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"example/graph/model"
)

// Unions is the resolver for the unions field.
func (r *queryResolver) Unions(ctx context.Context) ([]*model.Unions, error) {
	return []*model.Unions{
		&model.Unions{AbUnion: &model.A{
			Common: &model.CommonA{
				Test: 1,
			},
		}},
		&model.Unions{AbUnion: &model.A{
			Common: &model.CommonA{
				Test: 1,
			},
		}},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
